language: node_js
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
node_js:
  - stable
install:
  - yarn install
script:
  - yarn run test --no-watch --no-progress --browsers=ChromeHeadlessCI
